name: signature-verification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - asttokens
  - colorama
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - importlib-metadata
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - libffi
  - libsqlite
  - libzlib
  - matplotlib-inline
  - nest-asyncio
  - openssl
  - packaging
  - parso
  - pickleshare
  - platformdirs
  - prompt-toolkit
  - psutil
  - pure_eval
  - pygments
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zipp
  - pip:
      - absl-py
      - altair
      - astor
      - astunparse
      - attrs
      - base58
      - blinker
      - cachetools
      - certifi
      - charset-normalizer
      - click
      - contourpy
      - cycler
      - dominate
      - entrypoints
      - filelock
      - flatbuffers
      - fonttools
      - fsspec
      - gast
      - gitdb
      - gitpython
      - google-auth
      - google-auth-oauthlib
      - google-pasta
      - grpcio
      - h5py
      - idna
      - importlib-resources
      - jinja2
      - joblib
      - jsonpatch
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - keras
      - keras-preprocessing
      - kiwisolver
      - libclang
      - markdown
      - markupsafe
      - matplotlib
      - mpmath
      - networkx
      - numpy
      - oauthlib
      - opencv-python-headless
      - opt-einsum
      - pandas
      - pillow
      - protobuf
      - pyarrow
      - pyasn1
      - pyasn1-modules
      - pydeck
      - pympler
      - pyparsing
      - python-dateutil
      - pytz
      - pyyaml
      - referencing
      - requests
      - requests-oauthlib
      - rpds-py
      - rsa
      - scikit-learn
      - scipy
      - seaborn
      - smmap
      - streamlit
      - sympy
      - tensorboard
      - tensorboard-data-server
      - tensorboard-plugin-wit
      - tensorflow
      - tensorflow-estimator
      - tensorflow-io-gcs-filesystem
      - termcolor
      - thop
      - threadpoolctl
      - toml
      - toolz
      - torch
      - torchaudio
      - torchvision
      - tqdm
      - tzdata
      - tzlocal
      - urllib3
      - validators
      - visdom
      - watchdog
      - websocket-client
      - werkzeug
      - wrapt
