name: signature-verification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - asttokens=2.4.1
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.8
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - libffi
  - libsqlite
  - libzlib
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl
  - packaging=24.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - setuptools=75.5.0
  - six=1.16.0
  - sqlite
  - stack_data=0.6.2
  - tk
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.0
  - xz
  - zeromq
  - zipp=3.21.0
  - pip:
      - absl-py==2.1.0
      - altair==4.0.0
      - astor==0.8.1
      - astunparse==1.6.3
      - attrs==24.2.0
      - base58==2.1.1
      - blinker==1.9.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==7.1.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - dominate==2.9.1
      - entrypoints==0.4
      - filelock==3.16.1
      - flatbuffers==24.3.25
      - fonttools==4.55.0
      - fsspec==2024.10.0
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.36.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - grpcio==1.68.0
      - h5py==3.12.1
      - idna==3.10
      - importlib-resources==6.4.5
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - keras==3.6.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==2.0.2
      - oauthlib==3.2.2
      - opencv-python-headless==4.10.0.84
      - opt-einsum==3.4.0
      - pandas==2.2.3
      - pillow==11.0.0
      - protobuf==3.20.3
      - pyarrow==18.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydeck==0.9.1
      - pympler==1.1
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rpds-py==0.21.0
      - rsa==4.9
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - smmap==5.0.1
      - streamlit==1.3.1
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.18.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - thop==0.1.1.post2209072238
      - threadpoolctl==3.5.0
      - toml==0.10.2
      - toolz==1.0.0
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.0
      - tzdata==2024.2
      - tzlocal==5.2
      - urllib3==2.2.3
      - validators==0.34.0
      - visdom==0.2.4
      - watchdog==6.0.0
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wrapt==1.16.0
